using System;
using System.Collections.Generic;
using System.Text;

namespace BrutalAPI
{
    class Visuals
    {
        static public AttackVisualsSO Abandoned => LoadedDBsHandler.MiscDB.GetVisuals("Abandoned");
        static public AttackVisualsSO Absolve => LoadedDBsHandler.MiscDB.GetVisuals("Absolve");
        static public AttackVisualsSO BackBreaker => LoadedDBsHandler.MiscDB.GetVisuals("BackBreaker");
        static public AttackVisualsSO Bash => LoadedDBsHandler.MiscDB.GetVisuals("Bash");
        static public AttackVisualsSO Bellow => LoadedDBsHandler.MiscDB.GetVisuals("Bellow");
        static public AttackVisualsSO Blush => LoadedDBsHandler.MiscDB.GetVisuals("Blush");
        static public AttackVisualsSO Born => LoadedDBsHandler.MiscDB.GetVisuals("Born");
        static public AttackVisualsSO Bosch => LoadedDBsHandler.MiscDB.GetVisuals("Bosch");
        static public AttackVisualsSO Burn => LoadedDBsHandler.MiscDB.GetVisuals("Burn");
        static public AttackVisualsSO BurningPassion => LoadedDBsHandler.MiscDB.GetVisuals("BurningPassion");
        static public AttackVisualsSO Chomp => LoadedDBsHandler.MiscDB.GetVisuals("Chomp");
        static public AttackVisualsSO Clobber_Left => LoadedDBsHandler.MiscDB.GetVisuals("Clobber_Left");
        static public AttackVisualsSO Clobber_Right => LoadedDBsHandler.MiscDB.GetVisuals("Clobber_Right");
        static public AttackVisualsSO Coil => LoadedDBsHandler.MiscDB.GetVisuals("Coil");
        static public AttackVisualsSO ComeHome => LoadedDBsHandler.MiscDB.GetVisuals("ComeHome");
        static public AttackVisualsSO Conductor => LoadedDBsHandler.MiscDB.GetVisuals("Conductor");
        static public AttackVisualsSO Connection => LoadedDBsHandler.MiscDB.GetVisuals("Connection");
        static public AttackVisualsSO Contusion => LoadedDBsHandler.MiscDB.GetVisuals("Contusion");
        static public AttackVisualsSO Crush => LoadedDBsHandler.MiscDB.GetVisuals("Crush");
        static public AttackVisualsSO Cry => LoadedDBsHandler.MiscDB.GetVisuals("Cry");
        static public AttackVisualsSO Decimate => LoadedDBsHandler.MiscDB.GetVisuals("Decimate");
        static public AttackVisualsSO DemonCore => LoadedDBsHandler.MiscDB.GetVisuals("DemonCore");
        static public AttackVisualsSO Devour => LoadedDBsHandler.MiscDB.GetVisuals("Devour");
        static public AttackVisualsSO Doused => LoadedDBsHandler.MiscDB.GetVisuals("Doused");
        static public AttackVisualsSO Egg => LoadedDBsHandler.MiscDB.GetVisuals("Egg");
        static public AttackVisualsSO EndIt => LoadedDBsHandler.MiscDB.GetVisuals("EndIt");
        static public AttackVisualsSO Equal => LoadedDBsHandler.MiscDB.GetVisuals("Equal");
        static public AttackVisualsSO Excommunicate => LoadedDBsHandler.MiscDB.GetVisuals("Excommunicate");
        static public AttackVisualsSO Exsanguinate => LoadedDBsHandler.MiscDB.GetVisuals("Exsanguinate");
        static public AttackVisualsSO Extrusion => LoadedDBsHandler.MiscDB.GetVisuals("Extrusion");
        static public AttackVisualsSO FeelTheRhythm_Conductor => LoadedDBsHandler.MiscDB.GetVisuals("FeelTheRhythm_Conductor");
        static public AttackVisualsSO FeelTheRhythm => LoadedDBsHandler.MiscDB.GetVisuals("FeelTheRhythm");
        static public AttackVisualsSO FingerGuns => LoadedDBsHandler.MiscDB.GetVisuals("FingerGuns");
        static public AttackVisualsSO Flay => LoadedDBsHandler.MiscDB.GetVisuals("Flay");
        static public AttackVisualsSO Flex => LoadedDBsHandler.MiscDB.GetVisuals("Flex");
        static public AttackVisualsSO Genesis => LoadedDBsHandler.MiscDB.GetVisuals("Genesis");
        static public AttackVisualsSO Gnaw => LoadedDBsHandler.MiscDB.GetVisuals("Gnaw");
        static public AttackVisualsSO Gulp => LoadedDBsHandler.MiscDB.GetVisuals("Gulp");
        static public AttackVisualsSO Headshot => LoadedDBsHandler.MiscDB.GetVisuals("Headshot");
        static public AttackVisualsSO HeartBreaker => LoadedDBsHandler.MiscDB.GetVisuals("HeartBreaker");
        static public AttackVisualsSO Innocence => LoadedDBsHandler.MiscDB.GetVisuals("Innocence");
        static public AttackVisualsSO Insult => LoadedDBsHandler.MiscDB.GetVisuals("Insult");
        static public AttackVisualsSO Intrusion => LoadedDBsHandler.MiscDB.GetVisuals("Intrusion");
        static public AttackVisualsSO InvadeTheVeins => LoadedDBsHandler.MiscDB.GetVisuals("InvadeTheVeins");
        static public AttackVisualsSO Leech => LoadedDBsHandler.MiscDB.GetVisuals("Leech");
        static public AttackVisualsSO LifeLink => LoadedDBsHandler.MiscDB.GetVisuals("LifeLink");
        static public AttackVisualsSO Lighthouse => LoadedDBsHandler.MiscDB.GetVisuals("Lighthouse");
        static public AttackVisualsSO Lullaby => LoadedDBsHandler.MiscDB.GetVisuals("Lullaby");
        static public AttackVisualsSO Malpractice => LoadedDBsHandler.MiscDB.GetVisuals("Malpractice");
        static public AttackVisualsSO Mandibles => LoadedDBsHandler.MiscDB.GetVisuals("Mandibles");
        static public AttackVisualsSO Melt => LoadedDBsHandler.MiscDB.GetVisuals("Melt");
        static public AttackVisualsSO Messiah => LoadedDBsHandler.MiscDB.GetVisuals("Messiah");
        static public AttackVisualsSO Miracle => LoadedDBsHandler.MiscDB.GetVisuals("Miracle");
        static public AttackVisualsSO Misery => LoadedDBsHandler.MiscDB.GetVisuals("Misery");
        static public AttackVisualsSO Mitosis => LoadedDBsHandler.MiscDB.GetVisuals("Mitosis");
        static public AttackVisualsSO MotherlyLove => LoadedDBsHandler.MiscDB.GetVisuals("MotherlyLove");
        static public AttackVisualsSO Mould => LoadedDBsHandler.MiscDB.GetVisuals("Mould");
        static public AttackVisualsSO Mungle => LoadedDBsHandler.MiscDB.GetVisuals("Mungle");
        static public AttackVisualsSO Nibble => LoadedDBsHandler.MiscDB.GetVisuals("Nibble");
        static public AttackVisualsSO OilSlicked => LoadedDBsHandler.MiscDB.GetVisuals("OilSlicked");
        static public AttackVisualsSO Parry => LoadedDBsHandler.MiscDB.GetVisuals("Parry");
        static public AttackVisualsSO Poke => LoadedDBsHandler.MiscDB.GetVisuals("Poke");
        static public AttackVisualsSO Puke => LoadedDBsHandler.MiscDB.GetVisuals("Puke");
        static public AttackVisualsSO Pyre => LoadedDBsHandler.MiscDB.GetVisuals("Pyre");
        static public AttackVisualsSO Quills => LoadedDBsHandler.MiscDB.GetVisuals("Quills");
        static public AttackVisualsSO RejectDeath => LoadedDBsHandler.MiscDB.GetVisuals("RejectDeath");
        static public AttackVisualsSO RendRight => LoadedDBsHandler.MiscDB.GetVisuals("RendRight");
        static public AttackVisualsSO Resolve => LoadedDBsHandler.MiscDB.GetVisuals("Resolve");
        static public AttackVisualsSO RingABell => LoadedDBsHandler.MiscDB.GetVisuals("RingABell");
        static public AttackVisualsSO Scream => LoadedDBsHandler.MiscDB.GetVisuals("Scream");
        static public AttackVisualsSO Shank => LoadedDBsHandler.MiscDB.GetVisuals("Shank");
        static public AttackVisualsSO Shield => LoadedDBsHandler.MiscDB.GetVisuals("Shield");
        static public AttackVisualsSO Skewer => LoadedDBsHandler.MiscDB.GetVisuals("Skewer");
        static public AttackVisualsSO Slap => LoadedDBsHandler.MiscDB.GetVisuals("Slap");
        static public AttackVisualsSO Slash => LoadedDBsHandler.MiscDB.GetVisuals("Slash");
        static public AttackVisualsSO SliceAndDice => LoadedDBsHandler.MiscDB.GetVisuals("SliceAndDice");
        static public AttackVisualsSO Starve => LoadedDBsHandler.MiscDB.GetVisuals("Starve");
        static public AttackVisualsSO StompLeft => LoadedDBsHandler.MiscDB.GetVisuals("StompLeft");
        static public AttackVisualsSO StompRight => LoadedDBsHandler.MiscDB.GetVisuals("StompRight");
        static public AttackVisualsSO Strum => LoadedDBsHandler.MiscDB.GetVisuals("Strum");
        static public AttackVisualsSO Takedown => LoadedDBsHandler.MiscDB.GetVisuals("Takedown");
        static public AttackVisualsSO Talons => LoadedDBsHandler.MiscDB.GetVisuals("Talons");
        static public AttackVisualsSO Tango => LoadedDBsHandler.MiscDB.GetVisuals("Tango");
        static public AttackVisualsSO Tho => LoadedDBsHandler.MiscDB.GetVisuals("Tho");
        static public AttackVisualsSO Torched => LoadedDBsHandler.MiscDB.GetVisuals("Torched");
        static public AttackVisualsSO UglyOnTheInside => LoadedDBsHandler.MiscDB.GetVisuals("UglyOnTheInside");
        static public AttackVisualsSO Weep => LoadedDBsHandler.MiscDB.GetVisuals("Weep");
        static public AttackVisualsSO Womb => LoadedDBsHandler.MiscDB.GetVisuals("Womb");
        static public AttackVisualsSO Wriggle => LoadedDBsHandler.MiscDB.GetVisuals("Wriggle");
        static public AttackVisualsSO WrigglingWrath => LoadedDBsHandler.MiscDB.GetVisuals("WrigglingWrath");
        static public AttackVisualsSO Writhe => LoadedDBsHandler.MiscDB.GetVisuals("Writhe");
    }
}
